import { Package, CmsOption, HostingOption, AddOn } from "./types";

export const packages: Package[] = [
  {
    id: "start",
    name: "Webiro Start",
    oldPrice: 599,
    price: 449,
    savings: 150,
    badge: "Oplevering binnen 1 week",
    description: "Snel online met een professionele website",
    whatYouGet: [
      "1 pagina website",
      "SEO Start (title tags + meta descriptions)",
      "1 revisieronde",
    ],
    whyChoose: [
      "Ideaal voor starters",
      "Snel en betaalbaar online",
      "Alles eenvoudig op één pagina",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
    ],
  },
  {
    id: "groei",
    name: "Webiro Groei",
    oldPrice: 949,
    price: 749,
    savings: 200,
    badge: "Oplevering binnen 2 weken",
    description: "Alles wat je nodig hebt om klanten aan te trekken",
    popular: true,
    whatYouGet: [
      "Tot 5 pagina's",
      "SEO Groei (10 zoekwoorden + Google indexering)",
      "2 revisierondes",
    ],
    whyChoose: [
      "Meer ruimte voor diensten en info",
      "Professionelere uitstraling",
      "Perfect voor groeiende bedrijven",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
      "Social media integratie",
      "Google Maps integratie",
    ],
  },
  {
    id: "pro",
    name: "Webiro Pro",
    oldPrice: 1299,
    price: 999,
    savings: 300,
    badge: "Oplevering binnen 3 weken",
    description: "Maximale impact met geavanceerde SEO en uitstraling",
    whatYouGet: [
      "Tot 10 pagina's",
      "SEO Pro (15+ zoekwoorden + maandrapport)",
      "3 revisierondes",
    ],
    whyChoose: [
      "Uniek, professioneel ontwerp",
      "Verhoogt vertrouwen en conversies",
      "Ideaal voor grotere ambities",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
      "Social media integratie",
      "Google Maps integratie",
      "Blog/nieuwssectie",
      "Animaties & micro-interacties",
    ],
  },
  {
    id: "business",
    name: "Webiro Business",
    price: "Op aanvraag",
    badge: "Volledig maatwerk",
    description: "Maatwerk oplossingen voor complexere projecten",
    whatYouGet: [
      "10-20 pagina's volledig maatwerk",
      "Volledig custom design & branding",
      "Webshop/ledenportal/reserveringen",
      "Content Management Systeem",
    ],
    whyChoose: [
      "Volledige vrijheid in design",
      "Koppelingen met externe systemen",
      "Dedicated projectmanager",
    ],
  },
  {
    id: "shop",
    name: "Webiro Shop",
    price: "Op aanvraag",
    badge: "E-commerce",
    description: "Complete webshop oplossing voor je online verkoop",
    whatYouGet: [
      "Webshop tot 50 producten",
      "Betaalintegratie (iDEAL, Bancontact, etc.)",
      "Verzendopties & tarieven",
      "Voorraadbeheer systeem",
    ],
    whyChoose: [
      "Direct online verkopen",
      "Professionele checkout flow",
      "Volledige voorraad controle",
    ],
  },
];

export const cmsOptions: CmsOption[] = [
  {
    id: "geen",
    name: "Geen CMS",
    price: 0,
    description: "Wij beheren de content voor je. Ideaal als je weinig aanpassingen doet.",
    features: [
      "Wij voeren wijzigingen door",
      "Geen extra kosten",
      "Content wijzigingen op aanvraag",
    ],
  },
  {
    id: "basis",
    name: "Basis CMS",
    price: 149,
    description: "Beheer zelf eenvoudig je teksten en afbeeldingen.",
    features: [
      "Tekst & afbeeldingen aanpassen",
      "Gebruiksvriendelijk dashboard",
      "Handleiding inbegrepen",
    ],
    recommended: true,
  },
  {
    id: "uitgebreid",
    name: "Uitgebreid CMS",
    price: 299,
    description: "Volledige controle over je website content en structuur.",
    features: [
      "Pagina's toevoegen & bewerken",
      "Blog/nieuwsbeheer",
      "Media bibliotheek",
      "Gebruikersbeheer",
    ],
  },
];

export const hostingOptions: HostingOption[] = [
  {
    id: "basis",
    name: "Basis Hosting",
    price: 19,
    period: "per maand",
    description: "Betrouwbare hosting voor je website.",
    features: [
      "SSL-certificaat",
      "Dagelijkse backups",
      "99.9% uptime garantie",
      "5 e-mailadressen",
    ],
  },
  {
    id: "premium",
    name: "Premium Hosting",
    price: 39,
    period: "per maand",
    description: "Snelle hosting met extra's voor groeiende websites.",
    features: [
      "Alles van Basis",
      "CDN voor snellere laadtijden",
      "Onbeperkt e-mailadressen",
      "Priority support",
      "Maandelijkse updates",
    ],
    recommended: true,
  },
  {
    id: "managed",
    name: "Managed Hosting",
    price: 69,
    period: "per maand",
    description: "Zorgeloos online met volledig beheer.",
    features: [
      "Alles van Premium",
      "Maandelijks onderhoud & updates",
      "Performance monitoring",
      "Beveiligingsscans",
      "Dedicated accountmanager",
    ],
  },
];

export const addOns: AddOn[] = [
  {
    id: "google-ads",
    name: "Google Ads Setup",
    price: 299,
    period: "eenmalig",
    description: "Professionele Google Ads campagne opzetten",
    icon: "🎯",
    category: "marketing",
  },
  {
    id: "social-media",
    name: "Social Media Pakket",
    price: 199,
    period: "per maand",
    description: "Content creatie en beheer van je social media kanalen",
    icon: "📱",
    category: "marketing",
  },
  {
    id: "seo-maandelijks",
    name: "Maandelijkse SEO",
    price: 249,
    period: "per maand",
    description: "Continue SEO optimalisatie en rapportage",
    icon: "📈",
    category: "seo",
  },
  {
    id: "copywriting",
    name: "Professionele Copywriting",
    price: 349,
    period: "eenmalig",
    description: "SEO-geoptimaliseerde teksten voor je website",
    icon: "✍️",
    category: "seo",
  },
  {
    id: "fotografie",
    name: "Professionele Fotografie",
    price: 399,
    period: "eenmalig",
    description: "Professionele foto's voor je website",
    icon: "📸",
    category: "functionaliteit",
  },
  {
    id: "chat-widget",
    name: "Live Chat Widget",
    price: 99,
    period: "per maand",
    description: "Direct contact met je bezoekers via live chat",
    icon: "💬",
    category: "functionaliteit",
  },
  {
    id: "booking",
    name: "Online Boekingssysteem",
    price: 449,
    period: "eenmalig",
    description: "Laat klanten online afspraken inplannen",
    icon: "📅",
    category: "functionaliteit",
  },
  {
    id: "onderhoud",
    name: "Website Onderhoud",
    price: 79,
    period: "per maand",
    description: "Maandelijks onderhoud, updates en kleine aanpassingen",
    icon: "🔧",
    category: "onderhoud",
  },
];
