import { Package, CmsHostingTier, AddOn, MarketingService } from "./types";

export const packages: Package[] = [
  {
    id: "start",
    name: "Webiro Start",
    oldPrice: 599,
    price: 449,
    savings: 150,
    badge: "Oplevering binnen 1 week",
    description: "Snel online met een professionele website",
    whatYouGet: [
      "1 pagina website",
      "SEO Start (title tags + meta descriptions)",
      "1 revisieronde",
    ],
    whyChoose: [
      "Ideaal voor starters",
      "Snel en betaalbaar online",
      "Alles eenvoudig op één pagina",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
    ],
  },
  {
    id: "groei",
    name: "Webiro Groei",
    oldPrice: 949,
    price: 749,
    savings: 200,
    badge: "Oplevering binnen 2 weken",
    description: "Alles wat je nodig hebt om klanten aan te trekken",
    popular: true,
    whatYouGet: [
      "Tot 5 pagina's",
      "SEO Groei (10 zoekwoorden + Google indexering)",
      "2 revisierondes",
    ],
    whyChoose: [
      "Meer ruimte voor diensten en info",
      "Professionelere uitstraling",
      "Perfect voor groeiende bedrijven",
      "Schaalbaar voor toekomstige uitbreidingen",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
      "Social media integratie",
      "Google Maps integratie",
    ],
  },
  {
    id: "pro",
    name: "Webiro Pro",
    oldPrice: 1299,
    price: 999,
    savings: 300,
    badge: "Oplevering binnen 3 weken",
    description: "Maximale impact met geavanceerde SEO en uitstraling",
    whatYouGet: [
      "Tot 10 pagina's",
      "SEO Pro (15+ zoekwoorden + maandrapport)",
      "3 revisierondes",
    ],
    whyChoose: [
      "Uniek, professioneel ontwerp",
      "Verhoogt vertrouwen en conversies",
      "Ideaal voor grotere ambities",
      "Volledige vrijheid voor portfolio's, cases en funnels",
    ],
    details: [
      "Responsive design (mobiel, tablet, desktop)",
      "SSL-certificaat inbegrepen",
      "Contactformulier",
      "Google Analytics integratie",
      "Social media integratie",
      "Google Maps integratie",
      "Blog/nieuwssectie",
      "Animaties & micro-interacties",
    ],
  },
  {
    id: "business",
    name: "Webiro Business",
    price: "Op aanvraag",
    badge: "Volledig maatwerk",
    description: "Maatwerk oplossingen voor complexere projecten",
    whatYouGet: [
      "10-20 pagina's volledig maatwerk",
      "Volledig custom design & branding",
      "Webshop/ledenportal/reserveringen",
      "Content Management Systeem",
    ],
    whyChoose: [
      "Volledige vrijheid in design",
      "Koppelingen met externe systemen",
      "Dedicated projectmanager",
    ],
  },
  {
    id: "shop",
    name: "Webiro Shop",
    price: "Op aanvraag",
    badge: "E-commerce",
    description: "Complete webshop oplossing voor je online verkoop",
    whatYouGet: [
      "Webshop tot 50 producten",
      "Betaalintegratie (iDEAL, Bancontact, etc.)",
      "Verzendopties & tarieven",
      "Voorraadbeheer systeem",
    ],
    whyChoose: [
      "Direct online verkopen",
      "Professionele checkout flow",
      "Volledige voorraad controle",
    ],
  },
];

export const cmsHostingTiers: CmsHostingTier[] = [
  {
    id: "basic",
    name: "Webiro CMS Basic",
    price: 29,
    period: "per maand",
    description: "Perfecte basis voor startende ondernemers",
    features: [
      "Tot 10 pagina's beheren",
      "10 GB opslag",
      "Standaard SSL certificaat",
      "Dagelijkse backups (7 dagen)",
      "99.5% uptime garantie",
      "Email support (48u)",
      "Basis analytics dashboard",
      "Mobiel responsive",
    ],
  },
  {
    id: "pro",
    name: "Webiro CMS Pro",
    price: 49,
    period: "per maand",
    description: "Voor groeiende bedrijven met meer ambities",
    recommended: true,
    features: [
      "Onbeperkt pagina's beheren",
      "50 GB opslag",
      "Premium SSL certificaat",
      "Dagelijkse backups (30 dagen)",
      "99.9% uptime garantie",
      "Priority support (24u)",
      "Geavanceerde analytics",
      "SEO tools & optimalisatie",
      "Staging omgeving",
      "Custom domein email",
    ],
  },
  {
    id: "enterprise",
    name: "Webiro CMS Enterprise",
    price: "Op aanvraag",
    period: "vanaf €99/maand",
    description: "Alles van Pro, plus enterprise features",
    features: [
      "Alles van Pro",
      "Onbeperkte opslag",
      "Dedicated server optie",
      "99.99% uptime garantie",
      "24/7 support & live chat",
      "Multi-site beheer",
      "Custom integraties",
      "API toegang",
      "White-label mogelijkheden",
      "Persoonlijke account manager",
    ],
  },
  {
    id: "eigen",
    name: "CMS naar keuze",
    price: 0,
    period: "gratis",
    description: "Gebruik je eigen CMS platform en abonnement",
    features: [
      "WordPress, Webflow, Framer, Wix, Shopify of andere CMS",
      "Je regelt zelf het abonnement",
      "Webiro bouwt de website",
    ],
  },
];

export const addOns: AddOn[] = [
  // Onderhoud & Support
  {
    id: "webiro-care",
    name: "Webiro Care",
    price: 79,
    period: "per maand",
    description: "Onderhoud, updates en kleine aanpassingen",
    icon: "wrench",
    category: "onderhoud",
    features: [
      "Kleine aanpassingen (max 1 uur/maand)",
      "Technische updates & plugin updates",
      "Maandelijkse backup",
      "Prioriteit support (reactie binnen 24u)",
    ],
  },
  // Widgets (maandelijks)
  {
    id: "booking-widget",
    name: "Booking & Planner Widget",
    price: 24,
    period: "per maand",
    description: "Online afspraken plannen en beheren",
    icon: "calendar",
    category: "widgets",
    features: [
      "Kalender synchronisatie",
      "Email notificaties",
      "Automatische herinneringen",
      "Tijdzone ondersteuning",
      "Google Calendar sync",
      "iCal export",
    ],
  },
  {
    id: "ai-livechat",
    name: "AI Livechat Widget",
    price: 49,
    period: "per maand",
    description: "Intelligente chatbot met OpenAI integratie",
    icon: "message-circle",
    category: "widgets",
    features: [
      "GPT-4 AI assistent",
      "Automatische beantwoording",
      "Live agent overname",
      "Chat geschiedenis",
      "Custom branding",
      "Mobiel geoptimaliseerd",
    ],
  },
  // Marketing
  {
    id: "advertentie-management",
    name: "Advertentie Management",
    price: "Op aanvraag",
    period: "per maand",
    description: "Google Ads & Meta campagnes",
    icon: "megaphone",
    category: "marketing",
    features: [
      "Strategie & doelgroep targeting",
      "A/B testing & optimalisatie",
      "Maandelijkse rapportages & analytics",
      "Budget beheer & ROI tracking",
    ],
  },
  // Setup & Technisch
  {
    id: "domein-hosting-setup",
    name: "Domein & Hosting Setup",
    price: 99,
    period: "eenmalig",
    description: "Domeinregistratie, hosting & DNS configuratie",
    icon: "globe",
    category: "setup-technisch",
    features: [
      "Domeinregistratie assistentie",
      "Hosting configuratie & DNS",
      "E-mail accounts instellen",
    ],
  },
  {
    id: "email-setup",
    name: "Zakelijke E-mail Setup",
    price: 99,
    period: "eenmalig",
    description: "Professionele e-mail adressen configureren",
    icon: "mail",
    category: "setup-technisch",
    features: [
      "Professionele e-mail adressen",
      "E-mail client configuratie",
      "Handtekening template",
    ],
  },
  {
    id: "analytics-setup",
    name: "Google Analytics Setup",
    price: 249,
    period: "eenmalig",
    description: "Analytics account, tracking & rapportage",
    icon: "bar-chart-3",
    category: "setup-technisch",
    features: [
      "Analytics account aanmaken",
      "Tracking code installatie",
      "Conversie doelen configureren",
      "Basis rapportage dashboard",
    ],
  },
  // Functionaliteit & Integraties
  {
    id: "chatbot-integratie",
    name: "Chatbot Integratie",
    price: 499,
    period: "eenmalig",
    description: "Chatbot installatie, configuratie & design",
    icon: "🤖",
    category: "setup-functionaliteit",
    features: [
      "Chatbot installatie & configuratie",
      "Custom antwoorden & flows",
      "Design integratie",
      "Notificatie setup",
    ],
  },
  {
    id: "calendly-setup",
    name: "Calendly/Booking Setup",
    price: 199,
    period: "eenmalig",
    description: "Booking tool integratie & inrichting",
    icon: "📅",
    category: "setup-functionaliteit",
    features: [
      "Calendly of booking tool integratie",
      "Afspraak pagina volledig inrichten",
      "E-mail notificaties & reminders",
      "Design aanpassing",
    ],
  },
  {
    id: "specifieke-integraties",
    name: "Specifieke Integraties",
    price: 199,
    period: "eenmalig",
    description: "Mailchimp, Zapier, CRM & API koppelingen",
    icon: "🔗",
    category: "setup-functionaliteit",
    features: [
      "Mailchimp, Zapier, CRM koppelingen",
      "Custom API integraties",
      "Payment gateway setup",
      "Testing & documentatie",
    ],
  },
  // Design & Branding
  {
    id: "logo-design",
    name: "Logo Design",
    price: 249,
    period: "eenmalig",
    description: "Professioneel logo ontwerp met revisies",
    icon: "🎨",
    category: "setup-design",
    features: [
      "Professioneel logo ontwerp",
      "2 revisierondes",
      "Profielfoto's voor social media",
      "Alle bestandsformaten (PNG, SVG, JPG, PDF)",
    ],
  },
  {
    id: "bedrijfsnaam",
    name: "Bedrijfsnaam Strategisch Bedenken",
    price: 49,
    period: "eenmalig",
    description: "Strategisch naamadvies met domeincheck",
    icon: "💡",
    category: "setup-design",
    features: [
      "Strategisch naamadvies",
      "3-5 naam opties",
      "Domein beschikbaarheid check (.com & .nl)",
      "Merkregistratie advies",
    ],
  },
  {
    id: "branding-pakket",
    name: "Branding Pakket",
    price: 1499,
    period: "eenmalig",
    description: "Complete brandbook, kleurenpalet & templates",
    icon: "✨",
    category: "setup-design",
    features: [
      "Complete brandbook (digitaal)",
      "Kleurenpalet & typografie strategie",
      "Logo varianten & gebruiksrichtlijnen",
      "Social media templates",
      "Visitekaartje ontwerp",
      "E-mail handtekening template",
    ],
  },
  // Content & Compliance
  {
    id: "gdpr-pakket",
    name: "GDPR Pakket",
    price: 149,
    period: "eenmalig",
    description: "Privacy policy, cookie banner & disclaimer",
    icon: "🔒",
    category: "setup-content",
    features: [
      "Privacy policy & algemene voorwaarden",
      "Cookie banner installatie",
      "Disclaimer pagina",
    ],
  },
  {
    id: "content-schrijven",
    name: "Content Schrijven",
    price: 99,
    period: "eenmalig",
    description: "Professionele SEO-teksten per pagina",
    icon: "✍️",
    category: "setup-content",
    features: [
      "SEO-geoptimaliseerde teksten",
      "Professionele tone-of-voice",
      "Call-to-actions & conversiefocus",
      "1 revisieronde",
    ],
  },
];

export const addOnCategoryLabels: Record<string, string> = {
  "onderhoud": "🔧 Onderhoud & Support",
  "widgets": "🔌 Webiro Widgets (Maandelijks)",
  "marketing": "📣 Webiro Marketing",
  "setup-technisch": "⚙️ Setup — Technisch",
  "setup-functionaliteit": "⚙️ Setup — Functionaliteit & Integraties",
  "setup-design": "🎨 Setup — Design & Branding",
  "setup-content": "📄 Setup — Content & Compliance",
};

export const marketingServices: MarketingService[] = [
  {
    id: "google-ads",
    name: "Google Ads",
    monthlyPrice: 500,
    description: "Search & Display campagnes",
    category: "ads",
    features: [
      "Search & Display campagnes",
      "Keyword research & strategie",
      "A/B testing & optimalisatie",
    ],
  },
  {
    id: "meta-ads",
    name: "Meta Ads (Facebook & Instagram)",
    monthlyPrice: 500,
    description: "Facebook & Instagram campagnes",
    category: "ads",
    features: [
      "Facebook & Instagram campagnes",
      "Audience targeting & lookalikes",
      "Creative strategy",
    ],
  },
  {
    id: "tiktok-ads",
    name: "TikTok Ads",
    monthlyPrice: 500,
    description: "TikTok campagne setup",
    category: "ads",
    features: [
      "TikTok campagne setup",
      "Video advertising strategie",
      "Trend-based targeting",
    ],
  },
  {
    id: "email-automation",
    name: "E-mail Marketing Automation",
    setupPrice: 499,
    monthlyPrice: 79,
    description: "E-mail flows, welkom series & cart recovery",
    category: "automation",
    features: [
      "Welkom serie (3-5 emails)",
      "Abandoned cart recovery",
      "Lead nurturing sequence",
    ],
  },
  {
    id: "whatsapp-automation",
    name: "WhatsApp Automation",
    setupPrice: 499,
    monthlyPrice: 49,
    description: "Automatische follow-ups & order updates",
    category: "automation",
    features: [
      "Automatische follow-ups",
      "Order updates via WhatsApp",
      "Appointment reminders",
    ],
  },
  {
    id: "ai-chatbot",
    name: "AI Customer Support Chatbot",
    setupPrice: 699,
    monthlyPrice: 99,
    description: "GPT-4 powered chatbot, 24/7 beschikbaar",
    category: "ai",
    features: [
      "GPT-4 powered chatbot",
      "24/7 beschikbaar",
      "Getraind op jouw data",
    ],
  },
  {
    id: "lead-bot",
    name: "Lead Kwalificatie Bot",
    setupPrice: 499,
    monthlyPrice: 79,
    description: "Automatische lead scoring & kwalificatie",
    category: "ai",
    features: [
      "Automatische lead scoring",
      "Kwalificatie vragen flow",
      "CRM integratie",
    ],
  },
];

export const contractDiscounts: Record<string, { label: string; discount: number }> = {
  maandelijks: { label: "Maandelijks", discount: 0 },
  jaarlijks: { label: "Jaarlijks (–10%)", discount: 0.1 },
  "2jaar": { label: "2 jaar (–20%)", discount: 0.2 },
};
