ALTER TABLE public.monthly_data
  ADD COLUMN IF NOT EXISTS linkedin_spend numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_conversions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_ctr numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_cpc numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_impressions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_reach integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_frequency numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_link_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_lpv integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS linkedin_cpm numeric DEFAULT 0,

  ADD COLUMN IF NOT EXISTS pinterest_spend numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_conversions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_ctr numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_cpc numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_impressions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_reach integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_frequency numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_link_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_lpv integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pinterest_cpm numeric DEFAULT 0,

  ADD COLUMN IF NOT EXISTS youtube_spend numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_conversions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_ctr numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_cpc numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_impressions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_reach integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_frequency numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_link_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_lpv integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS youtube_cpm numeric DEFAULT 0,

  ADD COLUMN IF NOT EXISTS snapchat_spend numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_conversions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_ctr numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_cpc numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_impressions integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_reach integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_frequency numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_link_clicks integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_lpv integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapchat_cpm numeric DEFAULT 0;